--- 
- name: basic
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: whoami
      ansible.builtin.command: "ip a"
      register: iamwho

    - name: debug
      ansible.builtin.debug: 
        var: iamwho