name: firstWorkflow
run-name: First Workflow
on: [push]
jobs:
  firstWorkflowFirstJob:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: ansible-playbook -i inventory.yml basic.yml