name: Azure-CLI-Install
run-name: Azure CLI Install
on: 
  workflow_dispatch:
jobs:
  AzureCLIjob:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: ansible-playbook play-install-azure-cli.yml